(()=>{'use strict';
const URL='https://lidzkpdwhtbmplyhgbvw.supabase.co',KEY='sb_publishable_7d7DtFox5cLd7yvR7SkPZg_UE4fT_0K';
const db=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let rows=[],activeMission=null,activeStage=null,map=null,routeLayer=null,routePts=[],routeCumKm=[],routeElev=[],page=0,gesture=null,navigationLocked=false,mapLongPress=null,mapInteraction=false,currentPosition=null,ticker=null;
const show=id=>['auth','missionsView','stagesView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function num(v,...fallback){for(const x of [v,...fallback]){const n=Number(x);if(Number.isFinite(n))return n;}return 0;}
function fmtKm(v){return `${Math.max(0,v).toFixed(1).replace('.',',')} km`;}
function fmtM(v){return `${Math.max(0,Math.round(v))} m`;}
function fmtTime(sec){sec=Math.max(0,Math.round(sec||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;}
function clock(ts){return ts?new Date(ts).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'—';}
async function login(){const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});$('#authMsg').textContent=error?error.message:'';}
async function load(){const {data,error}=await db.from('missions').select('*').eq('metadata->>publishedToUltraCoach','true').order('updated_at',{ascending:false});if(error){$('#missions').innerHTML=`<div class="card">${esc(error.message)}</div>`;return;}rows=data||[];renderMissions();}
function renderMissions(){show('missionsView');$('#missions').innerHTML=rows.length?rows.map((r,i)=>`<button class="card mission ghost" data-mission="${i}"><strong>${esc(r.name)}</strong><span class="muted">${r.roadbook?.cuts?.length||0} étape(s)</span></button>`).join(''):'<div class="card muted">Aucune mission publiée.</div>';$$('[data-mission]').forEach(b=>b.onclick=()=>openMission(+b.dataset.mission));}
function openMission(i){activeMission=rows[i];$('#missionTitle').textContent=activeMission.name;const n=activeMission.roadbook?.cuts?.length||0;$('#stages').innerHTML=Array.from({length:n},(_,j)=>`<button class="card stage ghost" data-stage="${j}"><strong>Étape ${j+1}</strong><span class="muted">${esc(activeMission.roadbook?.stageDates?.[j]||'Prête')}</span></button>`).join('')||'<div class="card">Aucune étape préparée.</div>';$$('[data-stage]').forEach(b=>b.onclick=()=>openStage(+b.dataset.stage));show('stagesView');}
function stageData(i){const r=activeMission.roadbook||{},line=r.stageMissionEngine?.[i]?.line||[],strat=r.stageStrategies?.[i]||r.stageSimulations?.[i]||{},lodging=r.selectedLodgings?.[i]||null;return{index:i,line,strat,lodging,date:r.stageDates?.[i],departure:r.departureTimes?.[i]};}
function stateKey(){return `ucStageState:${activeMission?.id||activeMission?.name}:${activeStage?.index}`;}
function getState(){try{return JSON.parse(localStorage.getItem(stateKey()))||{status:'ready',startedAt:null,pausedAt:null,totalPausedMs:0,stoppedAt:null};}catch{return{status:'ready',startedAt:null,pausedAt:null,totalPausedMs:0,stoppedAt:null};}}
function saveState(s){localStorage.setItem(stateKey(),JSON.stringify(s));renderStageState();}
function startStage(){const s=getState();if(s.status==='paused'){s.totalPausedMs+=(Date.now()-s.pausedAt);s.pausedAt=null;s.status='running';}else if(s.status!=='running'){s.status='running';s.startedAt=Date.now();s.totalPausedMs=0;s.pausedAt=null;s.stoppedAt=null;}saveState(s);refreshPosition();}
function pauseStage(){const s=getState();if(s.status==='running'){s.status='paused';s.pausedAt=Date.now();saveState(s);}}
function stopStage(){if(!confirm('Arrêter définitivement cette étape ? Le chronomètre ne pourra pas reprendre sans réinitialisation.'))return;const s=getState();if(s.status==='paused')s.totalPausedMs+=(Date.now()-s.pausedAt);s.status='stopped';s.stoppedAt=Date.now();s.pausedAt=null;saveState(s);}
function elapsedMs(s=getState()){if(!s.startedAt)return 0;const end=s.status==='stopped'?s.stoppedAt:(s.status==='paused'?s.pausedAt:Date.now());return Math.max(0,end-s.startedAt-(s.totalPausedMs||0));}
function plannedDurationSec(){const s=activeStage.strat||{};const raw=s.durationSec||s.totalDurationSec||s.movingTimeSec;if(Number.isFinite(Number(raw)))return Number(raw);const text=String(s.durationText||s.totalTime||'');const hm=text.match(/(\d+)\s*h(?:\s*(\d+))?/i);if(hm)return (+hm[1]*3600)+(+hm[2]||0)*60;return 0;}
function totalDistance(){return num(activeStage.strat.distanceKm,activeStage.strat.distance,routeCumKm.at(-1));}
function totalElevation(){return num(activeStage.strat.elevationM,activeStage.strat.elevation,calcRouteElevation());}
function stageProgress(){const total=totalDistance();if(currentPosition&&routePts.length){const idx=nearestRouteIndex(currentPosition.lat,currentPosition.lon);const km=routeCumKm[idx]||0;return{km:Math.min(total,km),ratio:total?Math.min(1,km/total):0};}const s=getState(),dur=plannedDurationSec();const ratio=(s.startedAt&&dur)?Math.min(1,elapsedMs(s)/1000/dur):0;return{km:total*ratio,ratio};}
function renderStageState(){if(!activeStage)return;const s=getState(),running=s.status==='running',paused=s.status==='paused',stopped=s.status==='stopped';$('#startStage').textContent=paused?'▶ Reprendre':(running?'En cours':'▶ Démarrer');$('#startStage').disabled=running||stopped;$('#pauseStage').disabled=!running;$('#stopStage').disabled=!(running||paused);$('#stageStatus').textContent=stopped?'Terminée':paused?'En pause':running?'En cours':'Prête';$('#stageStatus').className=`status-pill ${s.status}`;const totalD=totalDistance(),totalE=totalElevation(),p=stageProgress(),doneE=totalE*p.ratio;$('#distanceDone').textContent=fmtKm(p.km);$('#distanceTotal').textContent=fmtKm(totalD);$('#distanceRemaining').textContent=fmtKm(totalD-p.km);$('#elevationDone').textContent=fmtM(doneE);$('#elevationTotal').textContent=fmtM(totalE);$('#elevationRemaining').textContent=fmtM(totalE-doneE);$('#departureClock').textContent=clock(s.startedAt);const dur=plannedDurationSec(),eta=s.startedAt&&dur?s.startedAt+(s.totalPausedMs||0)+dur*1000:null;$('#etaClock').textContent=clock(eta);$('#elapsedClock').textContent=fmtTime(elapsedMs(s)/1000);renderMissionLine();}
async function openStage(i){activeStage=stageData(i);$('#shell').classList.add('hidden');$('#cockpit').classList.remove('hidden');const l=activeStage.lodging;$('#lodging').innerHTML=l?`<h3>${esc(l.name||'Hébergement')}</h3><p>${esc([l.street||l.address,l.postcode,l.city].filter(Boolean).join(', '))}</p>${l.phone?`<p><a href="tel:${esc(l.phone)}">${esc(l.phone)}</a></p>`:''}${l.email?`<p><a href="mailto:${esc(l.email)}">${esc(l.email)}</a></p>`:''}${(l.lat&&l.lon)?`<p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${l.lat},${l.lon}">Ouvrir dans Google Maps</a></p>`:''}`:'<p class="muted">Aucun hébergement prévu.</p>';const rb=activeMission.roadbook||{},nut=rb.stageStrategies?.[i]?.nutrition||{};$('#nutrition').innerHTML=[['Glucides',nut.carbsPerHour||'—','g/h'],['Eau',nut.waterPerHourMl||'—','ml/h'],['Sodium',nut.sodiumPerHourMg||'—','mg/h']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="metric">${x[1]}</div><div>${x[2]}</div></div>`).join('');setupPages();await drawMap();renderStageState();clearInterval(ticker);ticker=setInterval(()=>{if(!document.hidden)renderStageState();},1000);refreshPosition();}
function isMealPoint(x){const blob=`${x.type||''} ${x.kind||''} ${x.role||''} ${x.category||''} ${x.name||''}`.toLowerCase();if(/meal|repas|déjeuner|dejeuner|dîner|diner|restaurant|ravito/.test(blob))return true;const m=String(x.time||'').match(/(\d{1,2}):(\d{2})/);if(!m)return false;const h=+m[1];return (h>=11&&h<=14)||(h>=18&&h<=21);}
function isArrival(x,idx,line){const blob=`${x.type||''} ${x.kind||''} ${x.role||''} ${x.name||''}`.toLowerCase();return idx===line.length-1||/arrivée|arrivee|finish|hébergement|hebergement/.test(blob);}
function timeForPoint(x,remainingKm){if(x.time)return x.time;const total=totalDistance(),dur=plannedDurationSec();if(!dur||!total)return '—';const sec=remainingKm/total*dur;return fmtTime(sec);}
function etaForPoint(x,remainingKm){if(x.time&&/^\d{1,2}:\d{2}$/.test(x.time))return x.time;const s=getState(),total=totalDistance(),dur=plannedDurationSec();if(!s.startedAt||!dur||!total)return '—';return clock(Date.now()+remainingKm/total*dur*1000);}
function selectedLinePoints(){const line=[...(activeStage.line||[])].sort((a,b)=>num(a.stageKm)-num(b.stageKm));const p=stageProgress().km;const future=line.filter(x=>num(x.stageKm)>=p-0.2);const next=future.filter((x,i)=>!isArrival(x,i,line)).slice(0,2);const meals=future.filter(isMealPoint);const arrival=line.length?line[line.length-1]:null;const all=[...next,...meals,...(arrival?[arrival]:[])];return all.filter((x,i,a)=>a.findIndex(y=>(y.name===x.name&&num(y.stageKm)===num(x.stageKm)))===i);}
function renderMissionLine(){if(!activeStage)return;const p=stageProgress().km,pts=selectedLinePoints();$('#missionLine').innerHTML=pts.length?pts.map((x,i)=>{const km=Math.max(0,num(x.stageKm)-p),arrival=isArrival(x,(activeStage.line||[]).indexOf(x),activeStage.line||[]),meal=isMealPoint(x),icon=arrival?'🏁':meal?'🍴':'🌭';return `<div class="card line-card"><div class="line-icon">${icon}</div><div><strong>${esc(x.name|| (arrival?'Arrivée':'Village'))}</strong><div class="line-values"><span>${fmtKm(km)}</span><span>${timeForPoint(x,km)}</span><span>${etaForPoint(x,km)}</span></div><div class="muted">Distance restante · temps restant · arrivée prévue</div></div></div>`;}).join(''):'<div class="card muted">Aucun village calculé.</div>';}
function haversine(a,b,c,d){const R=6371,p=Math.PI/180,da=(c-a)*p,db=(d-b)*p,q=Math.sin(da/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function nearestRouteIndex(lat,lon){let best=0,min=Infinity;routePts.forEach((p,i)=>{const d=(p[0]-lat)**2+(p[1]-lon)**2;if(d<min){min=d;best=i;}});return best;}
function calcRouteElevation(){let e=0;for(let i=1;i<routeElev.length;i++){const d=routeElev[i]-routeElev[i-1];if(d>0)e+=d;}return e;}
function emojiIcon(char,label){return L.divIcon({className:'emoji-marker',html:`<span title="${esc(label||'')}">${char}</span>`,iconSize:[34,34],iconAnchor:[17,17],popupAnchor:[0,-18]});}
async function drawMap(){if(map){map.remove();map=null;}routePts=[];routeCumKm=[];routeElev=[];map=L.map('map',{zoomControl:false,dragging:false,touchZoom:false,doubleClickZoom:false,scrollWheelZoom:false,boxZoom:false,keyboard:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);setupMapLongPress();const {data,error}=await db.storage.from('mission-gpx').download(activeMission.gpx_path);if(error||!data){map.setView([42.1,9.1],7);return;}const text=await data.text(),xml=new DOMParser().parseFromString(text,'application/xml'),nodes=[...xml.querySelectorAll('trkpt')];routePts=nodes.map(n=>[+n.getAttribute('lat'),+n.getAttribute('lon')]);routeElev=nodes.map(n=>num(n.querySelector('ele')?.textContent));routeCumKm=[0];for(let i=1;i<routePts.length;i++)routeCumKm[i]=routeCumKm[i-1]+haversine(...routePts[i-1],...routePts[i]);if(routePts.length){routeLayer=L.polyline(routePts).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[20,20]});}const line=activeStage.line||[];line.forEach((x,i)=>{if(!x.lat||!x.lon)return;const icon=isArrival(x,i,line)?emojiIcon('🏁',x.name):isMealPoint(x)?emojiIcon('🍴',x.name):null;if(icon)L.marker([x.lat,x.lon],{icon}).addTo(map).bindPopup(x.name||'Repère');});updateMapDynamicMarkers();renderStageState();}
function updateMapDynamicMarkers(){if(!map)return;map.eachLayer(layer=>{if(layer.options?.ucDynamic)map.removeLayer(layer);});const p=stageProgress().km;const line=[...(activeStage.line||[])].sort((a,b)=>num(a.stageKm)-num(b.stageKm));line.filter(x=>num(x.stageKm)>=p-0.2&&!isMealPoint(x)).slice(0,2).forEach(x=>{if(x.lat&&x.lon)L.marker([x.lat,x.lon],{icon:emojiIcon('🌭',x.name),ucDynamic:true}).addTo(map).bindPopup(x.name||'Prochain village');});if(currentPosition)L.marker([currentPosition.lat,currentPosition.lon],{icon:emojiIcon('🚲','Position actuelle'),ucDynamic:true}).addTo(map).bindPopup('Position actuelle');}
function refreshPosition(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(pos=>{currentPosition={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy};updateMapDynamicMarkers();renderStageState();},{},{enableHighAccuracy:false,timeout:12000,maximumAge:300000});}
function setupMapLongPress(){const el=$('#map');const cancel=()=>{clearTimeout(mapLongPress);mapLongPress=null;};el.addEventListener('touchstart',e=>{mapInteraction=false;cancel();mapLongPress=setTimeout(()=>{mapInteraction=true;gesture=null;map.dragging.enable();el.classList.add('map-moving');},500);},{passive:true});el.addEventListener('touchmove',e=>{if(!mapInteraction&&gesture){const t=e.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(Math.hypot(dx,dy)>10)cancel();}},{passive:true});const end=()=>{cancel();if(mapInteraction){setTimeout(()=>{map.dragging.disable();mapInteraction=false;el.classList.remove('map-moving');},60);}};el.addEventListener('touchend',end,{passive:true});el.addEventListener('touchcancel',end,{passive:true});}
function setupPages(){page=+(localStorage.getItem('ucLastPage')||0);const count=$$('#pages .page').length;$('#dots').innerHTML=Array.from({length:count},(_,i)=>`<button type="button" class="dot ${i===page?'active':''}" aria-label="Page ${i+1}" data-page="${i}"></button>`).join('');$$('[data-page]').forEach(d=>d.onclick=()=>goToPage(+d.dataset.page));movePage(false);}
function goToPage(next){if(navigationLocked||mapInteraction)return;const count=$$('#pages .page').length,target=Math.max(0,Math.min(count-1,next));if(target===page){movePage();return;}navigationLocked=true;page=target;movePage();setTimeout(()=>navigationLocked=false,260);}
function movePage(animate=true){const count=$$('#pages .page').length;page=Math.max(0,Math.min(count-1,page));const pages=$('#pages');if(!animate)pages.style.transition='none';pages.style.transform=`translate3d(-${page*100}vw,0,0)`;if(!animate)requestAnimationFrame(()=>pages.style.transition='');$$('.dot').forEach((d,i)=>d.classList.toggle('active',i===page));localStorage.setItem('ucLastPage',page);if(page===1&&map)setTimeout(()=>map.invalidateSize(),260);}
function startGesture(e){if($('#cockpit').classList.contains('hidden')||mapInteraction)return;const p=e.touches?e.touches[0]:e;gesture={x:p.clientX,y:p.clientY,time:Date.now(),horizontal:false,onMap:!!e.target.closest?.('#map')};}
function moveGesture(e){if(!gesture||mapInteraction)return;const p=e.touches?e.touches[0]:e,dx=p.clientX-gesture.x,dy=p.clientY-gesture.y;if(!gesture.horizontal&&Math.abs(dx)>8)gesture.horizontal=Math.abs(dx)>Math.abs(dy)*1.15;if(gesture.horizontal&&e.cancelable)e.preventDefault();}
function endGesture(e){if(!gesture||mapInteraction){gesture=null;return;}const p=e.changedTouches?e.changedTouches[0]:e,dx=p.clientX-gesture.x,dy=p.clientY-gesture.y,dt=Math.max(1,Date.now()-gesture.time),vx=Math.abs(dx)/dt,horizontal=Math.abs(dx)>Math.abs(dy)*1.15;gesture=null;if(horizontal&&(Math.abs(dx)>=32||vx>=0.35))goToPage(page+(dx<0?1:-1));}
const cockpit=$('#cockpit');cockpit.addEventListener('touchstart',startGesture,{passive:true,capture:true});cockpit.addEventListener('touchmove',moveGesture,{passive:false,capture:true});cockpit.addEventListener('touchend',endGesture,{passive:true,capture:true});cockpit.addEventListener('touchcancel',()=>gesture=null,{passive:true,capture:true});
$('#startStage').onclick=startStage;$('#pauseStage').onclick=pauseStage;$('#stopStage').onclick=stopStage;$('#login').onclick=login;$('#logout').onclick=()=>db.auth.signOut();$('#backMissions').onclick=renderMissions;$('#exitCockpit').onclick=()=>{clearInterval(ticker);$('#cockpit').classList.add('hidden');$('#shell').classList.remove('hidden');show('stagesView');};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&activeStage){refreshPosition();renderStageState();load();}});db.auth.onAuthStateChange((_e,s)=>s?load():show('auth'));db.auth.getSession().then(({data})=>data.session?load():show('auth'));if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js?v=1.0.0-alpha.3');})();
