(()=>{'use strict';
const URL='https://lidzkpdwhtbmplyhgbvw.supabase.co',KEY='sb_publishable_7d7DtFox5cLd7yvR7SkPZg_UE4fT_0K';
const db=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}),$=s=>document.querySelector(s);
let rows=[],activeMission=null,activeStage=null,map=null,routeLayer=null,page=0,touchX=0;
const show=id=>['auth','missionsView','stagesView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function login(){const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});$('#authMsg').textContent=error?error.message:'';}
async function load(){const {data,error}=await db.from('missions').select('*').eq('metadata->>publishedToUltraCoach','true').order('updated_at',{ascending:false});if(error){$('#missions').innerHTML=`<div class="card">${esc(error.message)}</div>`;return;}rows=data||[];renderMissions();}
function renderMissions(){show('missionsView');$('#missions').innerHTML=rows.length?rows.map((r,i)=>`<button class="card mission ghost" data-mission="${i}"><strong>${esc(r.name)}</strong><span class="muted">${r.roadbook?.cuts?.length||0} étape(s)</span></button>`).join(''):'<div class="card muted">Aucune mission publiée.</div>';document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>openMission(+b.dataset.mission));}
function openMission(i){activeMission=rows[i];$('#missionTitle').textContent=activeMission.name;const n=activeMission.roadbook?.cuts?.length||0;$('#stages').innerHTML=Array.from({length:n},(_,j)=>`<button class="card stage ghost" data-stage="${j}"><strong>Étape ${j+1}</strong><span class="muted">${esc(activeMission.roadbook?.stageDates?.[j]||'Prête')}</span></button>`).join('')||'<div class="card">Aucune étape préparée.</div>';document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>openStage(+b.dataset.stage));show('stagesView');}
function stageData(i){const r=activeMission.roadbook||{},line=r.stageMissionEngine?.[i]?.line||[],strat=r.stageStrategies?.[i]||r.stageSimulations?.[i]||{},lodging=r.selectedLodgings?.[i]||null;return{index:i,line,strat,lodging,date:r.stageDates?.[i],departure:r.departureTimes?.[i]};}
async function openStage(i){activeStage=stageData(i);$('#shell').classList.add('hidden');$('#cockpit').classList.remove('hidden');$('#navDistance').textContent=(activeStage.strat.distanceKm||activeStage.strat.distance||'—')+(activeStage.strat.distanceKm?' km':'');$('#navElevation').textContent=(activeStage.strat.elevationM||activeStage.strat.elevation||'—')+(activeStage.strat.elevationM?' m':'');$('#navPower').textContent=(activeStage.strat.targetPower||activeStage.strat.powerW||'—')+(activeStage.strat.targetPower||activeStage.strat.powerW?' W':'');$('#navDuration').textContent=activeStage.strat.durationText||activeStage.strat.totalTime||'—';$('#missionLine').innerHTML=activeStage.line.length?activeStage.line.map(x=>`<div class="card"><strong>${esc(x.name)}</strong><div class="muted">${esc(x.time||'')} · km ${Number(x.stageKm||0).toFixed(1)}</div></div>`).join(''):'<div class="card muted">Aucun village calculé.</div>';const l=activeStage.lodging;$('#lodging').innerHTML=l?`<h3>${esc(l.name||'Hébergement')}</h3><p>${esc([l.street||l.address,l.postcode,l.city].filter(Boolean).join(', '))}</p>${l.phone?`<p><a href="tel:${esc(l.phone)}">${esc(l.phone)}</a></p>`:''}${l.email?`<p><a href="mailto:${esc(l.email)}">${esc(l.email)}</a></p>`:''}${(l.lat&&l.lon)?`<p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${l.lat},${l.lon}">Ouvrir dans Google Maps</a></p>`:''}`:'<p class="muted">Aucun hébergement prévu.</p>';const rb=activeMission.roadbook||{},nut=rb.stageStrategies?.[i]?.nutrition||{};$('#nutrition').innerHTML=[['Glucides',nut.carbsPerHour||'—','g/h'],['Eau',nut.waterPerHourMl||'—','ml/h'],['Sodium',nut.sodiumPerHourMg||'—','mg/h']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="metric">${x[1]}</div><div>${x[2]}</div></div>`).join('');setupPages();await drawMap();}
async function drawMap(){if(map){map.remove();map=null;}map=L.map('map',{zoomControl:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);const {data,error}=await db.storage.from('mission-gpx').download(activeMission.gpx_path);if(error||!data){map.setView([42.1,9.1],7);return;}const text=await data.text(),xml=new DOMParser().parseFromString(text,'application/xml'),pts=[...xml.querySelectorAll('trkpt')].map(n=>[+n.getAttribute('lat'),+n.getAttribute('lon')]);if(pts.length){routeLayer=L.polyline(pts).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[20,20]});}activeStage.line.filter(x=>x.lat&&x.lon).forEach(x=>L.marker([x.lat,x.lon]).addTo(map).bindPopup(x.name));}
function setupPages(){page=+(localStorage.getItem('ucLastPage')||0);const count=$$('#pages .page').length;$('#dots').innerHTML=Array.from({length:count},(_,i)=>`<span class="dot ${i===page?'active':''}"></span>`).join('');movePage();}
function $$(s){return [...document.querySelectorAll(s)]}function movePage(){const count=$$('#pages .page').length;page=Math.max(0,Math.min(count-1,page));$('#pages').style.transform=`translateX(-${page*100}vw)`;$$('.dot').forEach((d,i)=>d.classList.toggle('active',i===page));localStorage.setItem('ucLastPage',page);if(page===1&&map)setTimeout(()=>map.invalidateSize(),230);}
$('#pages').addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});$('#pages').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>55){page+=dx<0?1:-1;movePage();}},{passive:true});
$('#login').onclick=login;$('#logout').onclick=()=>db.auth.signOut();$('#backMissions').onclick=renderMissions;$('#exitCockpit').onclick=()=>{$('#cockpit').classList.add('hidden');$('#shell').classList.remove('hidden');show('stagesView')};
db.auth.onAuthStateChange((_e,s)=>s?load():show('auth'));db.auth.getSession().then(({data})=>data.session?load():show('auth'));if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');})();